/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const timelineContainer: string;
const timelineBase: string;
const scrollContainer: string;
const scrollContent: string;
const hourGrid: string;
const hourLine: string;
const timeLabel: string;
const usageBlock: string;
const currentTimeIndicator: string;
const resizeHandle: string;
const top: string;
const bottom: string;
const appsList: string;
const appsHeader: string;
const appsContent: string;
const appItem: string;
const selected: string;
const appItemContent: string;
const appDot: string;
const appName: string;
const appMeta: string;
const emptyState: string;
const emptyStateIcon: string;
const sectionHeader: string;

export {
	timelineContainer,
	timelineBase,
	scrollContainer,
	scrollContent,
	hourGrid,
	hourLine,
	timeLabel,
	usageBlock,
	currentTimeIndicator,
	resizeHandle,
	top,
	bottom,
	appsList,
	appsHeader,
	appsContent,
	appItem,
	selected,
	appItemContent,
	appDot,
	appName,
	appMeta,
	emptyState,
	emptyStateIcon,
	sectionHeader
};

export default {
	timelineContainer,
	timelineBase,
	scrollContainer,
	scrollContent,
	hourGrid,
	hourLine,
	timeLabel,
	usageBlock,
	currentTimeIndicator,
	resizeHandle,
	top,
	bottom,
	appsList,
	appsHeader,
	appsContent,
	appItem,
	selected,
	appItemContent,
	appDot,
	appName,
	appMeta,
	emptyState,
	emptyStateIcon,
	sectionHeader
};
