/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const appBreakdownContainer: string;
const slideIn: string;
const slideInAnimation: string;

export {
	appBreakdownContainer,
	slideIn,
	slideInAnimation
};

export default {
	appBreakdownContainer,
	slideIn,
	slideInAnimation
};
