/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const focusButton: string;
const active: string;
const activeSession: string;
const sessionIcon: string;
const pulse: string;
const sessionInfo: string;
const sessionStatus: string;
const sessionTime: string;
const endButton: string;
const quickActions: string;
const startButton: string;
const startIcon: string;
const loader: string;
const spin: string;
const settingsLink: string;
const shortcutHint: string;

export {
	focusButton,
	active,
	activeSession,
	sessionIcon,
	pulse,
	sessionInfo,
	sessionStatus,
	sessionTime,
	endButton,
	quickActions,
	startButton,
	startIcon,
	loader,
	spin,
	settingsLink,
	shortcutHint
};

export default {
	focusButton,
	active,
	activeSession,
	sessionIcon,
	pulse,
	sessionInfo,
	sessionStatus,
	sessionTime,
	endButton,
	quickActions,
	startButton,
	startIcon,
	loader,
	spin,
	settingsLink,
	shortcutHint
};
