/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const sidebar: string;
const expand: string;
const ExpandBar: string;
const navList: string;
const sidebarExpanded: string;
const navItem: string;
const focusButton: string;
const link: string;
const linkActive: string;

export {
	sidebar,
	expand,
	ExpandBar,
	navList,
	sidebarExpanded,
	navItem,
	focusButton,
	link,
	linkActive
};

export default {
	sidebar,
	expand,
	ExpandBar,
	navList,
	sidebarExpanded,
	navItem,
	focusButton,
	link,
	linkActive
};
