/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const userBar: string;
const userInfo: string;
const userAvatar: string;
const title: string;

export {
	userBar,
	userInfo,
	userAvatar,
	title
};

export default {
	userBar,
	userInfo,
	userAvatar,
	title
};
