/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const header: string;
const focusSessionContainer: string;
const focusButton: string;
const active: string;
const pulse: string;
const focusIndicator: string;
const content: string;
const section: string;
const loading: string;
const spinner: string;
const spin: string;
const error: string;
const success: string;
const retryButton: string;
const appsGrid: string;
const appCard: string;
const appInfo: string;
const appName: string;
const appCategory: string;
const categoryDot: string;
const blockingControls: string;
const blockingSelect: string;
const statusIndicator: string;
const noApps: string;
const predefinedGrid: string;
const predefinedCard: string;
const predefinedInfo: string;
const predefinedName: string;
const predefinedDescription: string;
const urlPatterns: string;
const predefinedControls: string;
const toggleSwitch: string;
const toggleSlider: string;
const stats: string;
const statCard: string;
const statNumber: string;
const statLabel: string;

export {
	container,
	header,
	focusSessionContainer,
	focusButton,
	active,
	pulse,
	focusIndicator,
	content,
	section,
	loading,
	spinner,
	spin,
	error,
	success,
	retryButton,
	appsGrid,
	appCard,
	appInfo,
	appName,
	appCategory,
	categoryDot,
	blockingControls,
	blockingSelect,
	statusIndicator,
	noApps,
	predefinedGrid,
	predefinedCard,
	predefinedInfo,
	predefinedName,
	predefinedDescription,
	urlPatterns,
	predefinedControls,
	toggleSwitch,
	toggleSlider,
	stats,
	statCard,
	statNumber,
	statLabel
};

export default {
	container,
	header,
	focusSessionContainer,
	focusButton,
	active,
	pulse,
	focusIndicator,
	content,
	section,
	loading,
	spinner,
	spin,
	error,
	success,
	retryButton,
	appsGrid,
	appCard,
	appInfo,
	appName,
	appCategory,
	categoryDot,
	blockingControls,
	blockingSelect,
	statusIndicator,
	noApps,
	predefinedGrid,
	predefinedCard,
	predefinedInfo,
	predefinedName,
	predefinedDescription,
	urlPatterns,
	predefinedControls,
	toggleSwitch,
	toggleSlider,
	stats,
	statCard,
	statNumber,
	statLabel
};
