/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const header: string;
const loading: string;
const mainContent: string;
const timerSection: string;
const activeSession: string;
const circularTimer: string;
const timerCircle: string;
const progressRing: string;
const timerContent: string;
const timeDisplay: string;
const endSessionButton: string;
const sessionStats: string;
const sessionHeader: string;
const endButton: string;
const timerDisplay: string;
const timeRemaining: string;
const timeLabel: string;
const sessionInfo: string;
const sessionStat: string;
const stat: string;
const statValue: string;
const statLabel: string;
const progressBar: string;
const progressFill: string;
const startSection: string;
const startCircle: string;
const startContent: string;
const startTitle: string;
const durationDisplay: string;
const durationLabel: string;
const startInfo: string;
const jobRole: string;
const shortcutInfo: string;
const quickStart: string;
const startButton: string;
const shortcut: string;
const settings: string;
const settingsGrid: string;
const setting: string;
const settingValue: string;
const history: string;
const noHistory: string;
const historyList: string;
const historyItem: string;
const historyDate: string;
const historyDetails: string;
const historyDuration: string;
const historyRole: string;
const historyDistractions: string;
const historyStatus: string;
const active: string;
const completed: string;
const timerPreview: string;
const previewTime: string;
const previewLabel: string;
const jobRoleInfo: string;
const roleNote: string;
const timelineSection: string;
const timelineWrapper: string;

export {
	container,
	header,
	loading,
	mainContent,
	timerSection,
	activeSession,
	circularTimer,
	timerCircle,
	progressRing,
	timerContent,
	timeDisplay,
	endSessionButton,
	sessionStats,
	sessionHeader,
	endButton,
	timerDisplay,
	timeRemaining,
	timeLabel,
	sessionInfo,
	sessionStat,
	stat,
	statValue,
	statLabel,
	progressBar,
	progressFill,
	startSection,
	startCircle,
	startContent,
	startTitle,
	durationDisplay,
	durationLabel,
	startInfo,
	jobRole,
	shortcutInfo,
	quickStart,
	startButton,
	shortcut,
	settings,
	settingsGrid,
	setting,
	settingValue,
	history,
	noHistory,
	historyList,
	historyItem,
	historyDate,
	historyDetails,
	historyDuration,
	historyRole,
	historyDistractions,
	historyStatus,
	active,
	completed,
	timerPreview,
	previewTime,
	previewLabel,
	jobRoleInfo,
	roleNote,
	timelineSection,
	timelineWrapper
};

export default {
	container,
	header,
	loading,
	mainContent,
	timerSection,
	activeSession,
	circularTimer,
	timerCircle,
	progressRing,
	timerContent,
	timeDisplay,
	endSessionButton,
	sessionStats,
	sessionHeader,
	endButton,
	timerDisplay,
	timeRemaining,
	timeLabel,
	sessionInfo,
	sessionStat,
	stat,
	statValue,
	statLabel,
	progressBar,
	progressFill,
	startSection,
	startCircle,
	startContent,
	startTitle,
	durationDisplay,
	durationLabel,
	startInfo,
	jobRole,
	shortcutInfo,
	quickStart,
	startButton,
	shortcut,
	settings,
	settingsGrid,
	setting,
	settingValue,
	history,
	noHistory,
	historyList,
	historyItem,
	historyDate,
	historyDetails,
	historyDuration,
	historyRole,
	historyDistractions,
	historyStatus,
	active,
	completed,
	timerPreview,
	previewTime,
	previewLabel,
	jobRoleInfo,
	roleNote,
	timelineSection,
	timelineWrapper
};
