/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const projectsPage: string;
const header: string;
const titleSection: string;
const titleIcon: string;
const subtitle: string;
const featuresGrid: string;
const featureCard: string;
const featureIcon: string;
const targetAudience: string;
const audienceText: string;
const highlight: string;
const emptyState: string;
const emptyIcon: string;
const createButton: string;
const buttonIcon: string;
const projectsList: string;

export {
	projectsPage,
	header,
	titleSection,
	titleIcon,
	subtitle,
	featuresGrid,
	featureCard,
	featureIcon,
	targetAudience,
	audienceText,
	highlight,
	emptyState,
	emptyIcon,
	createButton,
	buttonIcon,
	projectsList
};

export default {
	projectsPage,
	header,
	titleSection,
	titleIcon,
	subtitle,
	featuresGrid,
	featureCard,
	featureIcon,
	targetAudience,
	audienceText,
	highlight,
	emptyState,
	emptyIcon,
	createButton,
	buttonIcon,
	projectsList
};
