/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const questionnaireContainer: string;
const questionnaireCard: string;
const slideUp: string;
const header: string;
const title: string;
const subtitle: string;
const form: string;
const questionGroup: string;
const questionLabel: string;
const input: string;
const select: string;
const checkboxGroup: string;
const checkboxItem: string;
const checkbox: string;
const checkmark: string;
const checkboxLabel: string;
const radioGroup: string;
const radioItem: string;
const radio: string;
const radiomark: string;
const radioLabel: string;
const buttonGroup: string;
const button: string;
const primaryButton: string;
const secondaryButton: string;
const progressBar: string;
const progressFill: string;
const stepIndicator: string;
const errorMessage: string;
const loadingSpinner: string;
const spin: string;
const customInput: string;
const fadeIn: string;

export {
	questionnaireContainer,
	questionnaireCard,
	slideUp,
	header,
	title,
	subtitle,
	form,
	questionGroup,
	questionLabel,
	input,
	select,
	checkboxGroup,
	checkboxItem,
	checkbox,
	checkmark,
	checkboxLabel,
	radioGroup,
	radioItem,
	radio,
	radiomark,
	radioLabel,
	buttonGroup,
	button,
	primaryButton,
	secondaryButton,
	progressBar,
	progressFill,
	stepIndicator,
	errorMessage,
	loadingSpinner,
	spin,
	customInput,
	fadeIn
};

export default {
	questionnaireContainer,
	questionnaireCard,
	slideUp,
	header,
	title,
	subtitle,
	form,
	questionGroup,
	questionLabel,
	input,
	select,
	checkboxGroup,
	checkboxItem,
	checkbox,
	checkmark,
	checkboxLabel,
	radioGroup,
	radioItem,
	radio,
	radiomark,
	radioLabel,
	buttonGroup,
	button,
	primaryButton,
	secondaryButton,
	progressBar,
	progressFill,
	stepIndicator,
	errorMessage,
	loadingSpinner,
	spin,
	customInput,
	fadeIn
};
