/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const timelineContainer: string;
const timelineBase: string;
const scrollContainer: string;
const scrollContent: string;
const timeStops: string;
const dataRails: string;
const groupedDataRail: string;
const projectDataRail: string;
const calanderDataRail: string;
const dataRailHeaderContainer: string;
const dataRailHeader: string;
const categoryItem: string;
const categoryTags: string;
const categoryTag: string;

export {
	timelineContainer,
	timelineBase,
	scrollContainer,
	scrollContent,
	timeStops,
	dataRails,
	groupedDataRail,
	projectDataRail,
	calanderDataRail,
	dataRailHeaderContainer,
	dataRailHeader,
	categoryItem,
	categoryTags,
	categoryTag
};

export default {
	timelineContainer,
	timelineBase,
	scrollContainer,
	scrollContent,
	timeStops,
	dataRails,
	groupedDataRail,
	projectDataRail,
	calanderDataRail,
	dataRailHeaderContainer,
	dataRailHeader,
	categoryItem,
	categoryTags,
	categoryTag
};
