/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const container: string;
const header: string;
const headerActions: string;
const createButton: string;
const resetButton: string;
const content: string;
const sidebar: string;
const categoryList: string;
const categoryItem: string;
const selected: string;
const categoryColor: string;
const categoryInfo: string;
const categoryName: string;
const categoryCount: string;
const categoryActions: string;
const editButton: string;
const deleteButton: string;
const main: string;
const categoryDetails: string;
const categoryHeader: string;
const categoryTitleRow: string;
const appsSection: string;
const appsList: string;
const appItem: string;
const appName: string;
const categorySelect: string;
const placeholder: string;
const loading: string;
const loadingIcon: string;
const spin: string;
const error: string;
const retryButton: string;
const modal: string;
const modalContent: string;
const formGroup: string;
const colorPicker: string;
const colorPresets: string;
const colorPreset: string;
const modalActions: string;
const saveButton: string;
const cancelButton: string;

export {
	container,
	header,
	headerActions,
	createButton,
	resetButton,
	content,
	sidebar,
	categoryList,
	categoryItem,
	selected,
	categoryColor,
	categoryInfo,
	categoryName,
	categoryCount,
	categoryActions,
	editButton,
	deleteButton,
	main,
	categoryDetails,
	categoryHeader,
	categoryTitleRow,
	appsSection,
	appsList,
	appItem,
	appName,
	categorySelect,
	placeholder,
	loading,
	loadingIcon,
	spin,
	error,
	retryButton,
	modal,
	modalContent,
	formGroup,
	colorPicker,
	colorPresets,
	colorPreset,
	modalActions,
	saveButton,
	cancelButton
};

export default {
	container,
	header,
	headerActions,
	createButton,
	resetButton,
	content,
	sidebar,
	categoryList,
	categoryItem,
	selected,
	categoryColor,
	categoryInfo,
	categoryName,
	categoryCount,
	categoryActions,
	editButton,
	deleteButton,
	main,
	categoryDetails,
	categoryHeader,
	categoryTitleRow,
	appsSection,
	appsList,
	appItem,
	appName,
	categorySelect,
	placeholder,
	loading,
	loadingIcon,
	spin,
	error,
	retryButton,
	modal,
	modalContent,
	formGroup,
	colorPicker,
	colorPresets,
	colorPreset,
	modalActions,
	saveButton,
	cancelButton
};
