/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const controlsContainer: string;
const focusButton: string;
const link: string;

export {
	controlsContainer,
	focusButton,
	link
};

export default {
	controlsContainer,
	focusButton,
	link
};
