/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const categoryGraph: string;
const graphContainer: string;
const pieChartContainer: string;
const pieChart: string;
const pieSegment: string;
const centerCircle: string;
const totalTime: string;
const totalLabel: string;
const legend: string;
const legendItem: string;
const legendColor: string;
const legendInfo: string;
const legendCategory: string;
const legendTime: string;
const summary: string;

export {
	categoryGraph,
	graphContainer,
	pieChartContainer,
	pieChart,
	pieSegment,
	centerCircle,
	totalTime,
	totalLabel,
	legend,
	legendItem,
	legendColor,
	legendInfo,
	legendCategory,
	legendTime,
	summary
};

export default {
	categoryGraph,
	graphContainer,
	pieChartContainer,
	pieChart,
	pieSegment,
	centerCircle,
	totalTime,
	totalLabel,
	legend,
	legendItem,
	legendColor,
	legendInfo,
	legendCategory,
	legendTime,
	summary
};
